version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - gateway

  gateway:
    build:
      context: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth
      - product
      - order
    env_file:
      - ./gateway/.env

  auth:
    build:
      context: ./services/auth
    ports:
      - "8001:8001"
    env_file:
      - ./services/auth/.env

  product:
    build:
      context: ./services/product
    ports:
      - "8002:8002"
    env_file:
      - ./services/product/.env

  order:
    build:
      context: ./services/order
    ports:
      - "8003:8003"
    env_file:
      - ./services/order/.env
